#!/usr/bin/env python3
"""Generate the anti-aliased digit font of the BOX-Lite LCD view.

Renders 0-9 and '-' from a TrueType font (DejaVu Sans Bold) into 4-bit
alpha glyphs of fixed height, written as main/targets/esp32s3/lcd_font.h.
Requires Pillow. The font's license text is copied into the header.
"""
import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

CHARS = '0123456789-'


def render(font_path, height, size):
    font = ImageFont.truetype(str(font_path), size)
    top = min(font.getbbox(c)[1] for c in CHARS)
    glyphs = []
    for c in CHARS:
        advance = round(font.getlength(c))
        image = Image.new('L', (advance, height), 0)
        ImageDraw.Draw(image).text((0, -top), c, font=font, fill=255)
        glyphs.append((c, advance, [[image.getpixel((x, y)) * 15 // 255 for x in range(advance)]
                                    for y in range(height)]))
    return glyphs


def header(glyphs, height, font_name, license_text):
    out = ['/* Generated by tools/gen_lcd_font.py from %s; do not edit.' % font_name,
           ' * 4-bit alpha, two pixels per byte (high nibble first), rows of',
           ' * ceil(width / 2) bytes. Glyph bitmaps derive from the font below.',
           ' *']
    out += [(' * ' + line).rstrip() for line in license_text.splitlines()]
    out += [' */', '#pragma once', '#include <stdint.h>', '',
            '#define LCD_FONT_H %d' % height, '#define LCD_FONT_CHARS "%s"' % CHARS, '',
            'typedef struct { uint8_t width; uint16_t offset; } lcd_font_glyph_t;', '']
    data, table = [], []
    for c, width, rows in glyphs:
        table.append('    {%d, %d}, /* %s */' % (width, len(data), c))
        for row in rows:
            row = row + [0] * (len(row) % 2)
            data += [row[i] << 4 | row[i + 1] for i in range(0, len(row), 2)]
    out.append('static const lcd_font_glyph_t lcd_font_glyphs[] = {')
    out += table
    out.append('};')
    out.append('static const uint8_t lcd_font_data[] = {')
    for i in range(0, len(data), 16):
        out.append('    ' + ','.join('0x%02x' % b for b in data[i:i + 16]) + ',')
    out.append('};')
    return '\n'.join(out) + '\n'


def main():
    root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('font', type=Path, help='DejaVuSans-Bold.ttf')
    parser.add_argument('license', type=Path, help="the font's LICENSE file")
    parser.add_argument('--height', type=int, default=16)
    parser.add_argument('--size', type=int, default=21, help='font size in pixels')
    parser.add_argument('--output', type=Path, default=root / 'main/targets/esp32s3/lcd_font.h')
    a = parser.parse_args()
    glyphs = render(a.font, a.height, a.size)
    a.output.write_text(header(glyphs, a.height, a.font.name, a.license.read_text()))


if __name__ == '__main__':
    main()
